### ISSUE TITLE
Saluki: `μflux` API?

### ISSUE THREAD

**Issue by Isweet** [BinaryAnalysisPlatform/bap-plugins#26]
Hey,

We are interested in the `μflux` analysis built into the Saluki plugin. We'd like to use the data-flow facts generated in our own tool. Is there an API somewhere? Is this part of the Saluki plugin or BAP proper?

A pointer to the appropriate `.mli` file would be much appreciated.

Thanks!

**Comment by ivg** [comment]
Yes this part of BAP is proper, however it is superseded with the new Primus Framework which is much more general. So, you should also consider switching to Primus, depending on your task.

Concerning Saluki, it looks into term attributes for dataflow facts, so you can use any dataflow analysis, and then run Saluki as a policy checker. That was the whole original purpose for the development of this tool :)

The attributes that Saluki is looking for a declared in [this module][1]. To attach an attribute to a term use the [Term.set_attr][2] function. As you may see there are 4 different kind of attributes. The first two are use to specify the sources of taint:

- `Taint.reg x` attached to a term means that computation of this term produces a value that is tainted by the strain `x`, (usually `x` is the tid of the term itself, but it maybe different, which is useful if a term acts as a proxy to the real source, e.g., when it is a callsite)

- `Taint.ptr x` is the same as `reg` except that the term produces a value, which is a pointer to a value which is tainted by the strain `x`, and so on.

The second two are used to specify tainted values:

- `Taint.regs taints` when attached to a term `t` gives a mapping `strains = taints[v]` where `v` is a free variable in `t`, and `strains` is a set of taint strains associated with this variable. 

- `Taint.ptrs taints` is again the same, but refers to the tainted that are referenced indirectly.

If your analysis is not that precise, and can't track taints to individual parameters it is fine to just map all free variables in a term to identified taints. 

[1]: http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Taint.html
[2]: http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Term.html#VALset_attr

**Comment by Isweet** [comment]
Thanks!

I don't know anything about BAP plugins, so I'll follow the tutorial and see if that's enough to figure out how to do what I need to do.

Closing this issue, and will open another one on the BAP repository if I need more help.

**Comment by ivg** [comment]
you're welcome, consider dropping by our [gitter][1] or [discord][2] channels. 

[1]: https://gitter.im/BinaryAnalysisPlatform/bap
[2]: https://discord.gg/bwJ3p7q
